# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20160229_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 10, 35, 30, 729110, tzinfo=utc), verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
